version: '3'
services:
  base:
    build:
      context: '.'
      dockerfile: 'Dockerfile-Base'
      args:
        arg_ssh_user_pwd: 'root:1234'
        arg_time_zone: 'America/Los_Angeles'
        arg_ntp_server_0: 'server 0.us.pool.ntp.org'
        arg_ntp_server_1: 'server 1.us.pool.ntp.org'
        arg_dir_project: 'GAME'
    image: "tetris-server/base:${X_BASE_TAG}"
  app:
    depends_on:
      - base
    build:
      context: '.'
      dockerfile: 'Dockerfile-App'
      args:
        arg_base_tag: "${X_BASE_TAG}"
    image: "tetris-server/app:${X_APP_TAG}"
    container_name: 'app'
    hostname: 'app'
    ports:
     - '2222:22'
     - "8888:${X_SERVER_PORT}"
